name: Auto
on: 
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  
jobs:
  tagcreate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git pull
      - uses: The-Catalyst-Browser-Project/ci-auto-release@main
      - name: Push
        run: |
          git pull
          git push --follow-tags
  build:
    needs: tagcreate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Get tailwind styles
        run: npm run tailwind:once
      - name: Publish to release using Electron Forge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
      - name: Apple Silicon
        if: ${{ matrix.os == 'macos-latest' }}
        run: npm run publish -- --arch=arm64
  build32:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Get tailwind styles
        run: npm run tailwind:once
      - name: Publish to release using Electron Forge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish -- --arch=ia32
